name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build:
    name: x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"
          architecture: x64

      - name: intall virtualenv
        run: pip install virtualenv

      - name: Install python dependencies
        run: make env

      - name: Run linting
        run: make lint

      - name: Generate documentation
        run: make doc
